updated to `fun <T, C : Closeable> C?.useOrCreateAndClose, created fun <T> SQLiteDatabase.transaction(code: SQLiteDatabase.() -> T) : T?`,
created

```
fun <T> SQLiteDatabase.transaction(
    throwException: Boolean = false,
    code: SQLiteDatabase.() -> T
) : T?
```